### ISSUE TITLE
Implement a more complete LightComponent

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#35]
LightComponent currently is really bare. It should be documented and more events and methods should be implemented like SetAmbientColor, SetSpecularColor, Activate, Deactivate, SetIntensity. Of course it will also need getters for all of those.

**Comment by opatut** [comment]
Actually, activate and deactivate have to be implemented in the Component directly for all other Components.

**Comment by EternalWind** [comment]
Hey opatut. You told me to write a OnSwitch() function in the LightComponent class and then use it to call the OnSwitch() function of the LightComponentListener. Then the OnSwitch() of the listener will call the _CallSignal() function. However, the pointer of the listener is a instance of the ComponentListener base class which does not contain a interface for the custom On****(). So using the mListener can't call the OnSwitch() of the listener.

**Comment by opatut** [comment]
Actually, it is a std::shared_ptr<ComponentListener>. This does not matter anymore, because we completely remove ComponentListeners from the whole engine. You can see how it should work now [on this wiki page](https://github.com/ducttape/ducttape-engine/wiki/Nodes-and-Components). Just pull the latest changes from master. Not the _CallSignal() method has moved into the components and you gotta put the `virtual void OnSwitch()` in the Component, too. Don't do anything inside, though, just call it alongside with `_CallSignal("Switch")` so people can override it in inherited classes.

```
class LightComponent : public Component {
    // your stuff here
    virtual void OnSwitch() {}

    void Switch() {
        // switch it
        OnSwitch();
        _CallSignal("Switch");
    }
}
```

Feel free to ask in IRC (new channel: #ducttape-dev) if you have questions about that.

**Comment by EternalWind** [comment]
Got it. Thanks.

**Comment by svenstaro** [comment]
Seems to be done. Thanks EternalWind!
