### ISSUE TITLE
Consider removing the ComponentListeners

### ISSUE THREAD

**Issue by svenstaro** [ducttape/ducttape-engine#37]
Instead of having extra ComponentListeners per component, why not just put the signal/slot stuff into Component directly? It would take out a lot of confusion for beginners since Components are EventListeners and ComponentListeners are ComponentListeners. It would also save us some code. I think Components are generally clean enough to begin with.

What do you think?

**Comment by opatut** [comment]
http://ducttape-dev.org/docs/d4/d1f/Components.html

The way it is right now allows for reuse of inherited ComponentListeners in multiple components of the same type. Otherwise you would have to write some hacky on-construct signal binding, which is not at all a great design.

Imagine the Trigger component that has to check on-trigger if the player who triggered is allowed to &lt;whatever is being triggered, e.g open a door>. You could write a TriggerComponentListener for that instead of always checking manually.

**Comment by opatut** [comment]
Actually, if we move the _CallSignal() alongside the mListner.Something() and remove the listener to call Something in the class itself, we save a lot of code _and_ we can inherit from the component directly.
